[project]
name = "langchainlearn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain[google-genai]>=1.2.1",
    "python-dotenv>=1.2.1",
]
